/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import static esecuele.conexion.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import vistaAdmin.Menu_admin;
import vistaBecario.Menu_bec;

/**
 *
 * @author Eddie
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        campoNombreUsuario = new javax.swing.JTextField();
        nombeUsuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoContraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campoContraseña.setForeground(new java.awt.Color(0, 204, 204));
        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(campoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, 40));
        getContentPane().add(campoNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 30));

        nombeUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombeUsuario.setText("Nombre de Usuario");
        getContentPane().add(nombeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        contraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contraseña.setText("Contraseña");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2_.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = getConnection();
        String nombreUsuario = campoNombreUsuario.getText();
        String contraseña = campoContraseña.getText();
        String sql = "SELECT * FROM usuarios WHERE nombre = ? AND contraseña = ?";
        ResultSet rs;
        if (nombreUsuario.equals("") || contraseña.equals("")) {
            JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
        } else {
            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, nombreUsuario);
                ps.setString(2, contraseña);
                rs = ps.executeQuery();
                if (rs.next()) {
                    String sl = rs.getString("nivelPrivilegio");
                    switch (sl) {
                        case "Administrador":
                            Menu_admin ventanaAdmin = new Menu_admin();
                            ventanaAdmin.setVisible(true);
                            this.setVisible(false);
                            break;
                        case "Estándar":
                            Menu_bec ventanaBecario = new Menu_bec();
                            ventanaBecario.setVisible(true);
                            this.setVisible(false);
                            break;
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombeUsuario;
    // End of variables declaration//GEN-END:variables
}
